---
title: "Xonotic: The Free and Fast Arena Shooter"
indexes:
  category: "categories"
  tag: "tags"
baseurl: "https://xonotic.org/"
markup:
  goldmark:
    renderer:
      # xonotic.org includes inline html which is disabled by default in goldmark
      unsafe: true
---
